config/routes.rb
Rails.application.routes.draw do
  resources :hugs
  resources :orders
end

app/models/hug.rb
class Hug < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :hug

  def process_payment
	customer = Stripe::Customer.create(
		email: email,
		card: card_token
		
	)

	charge = Stripe::Charge.create(
		:customer    => customer.id,
		:amount      => hug.price * 100,
		:description => hug.name,
		:currency    => 'usd'
	)

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to charges_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hugs_controller.rb
class HugsController < ApplicationController

	def index
		@hugs = Hug.all
	end

	def create
	end

	def show
		@hug = Hug.find(params[:id])
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def new
		@hug = Hug.find(params[:hug_id])
		@order = Order.new
	end

	def create
		@order = Order.new orders_param.merge(email: stripe_params["stripeEmail"],card_token: stripe_params["stripeToken"])
		@order.process_payment

		@order.save
	end

	private
    def stripe_params
      params.permit :stripeEmail, :stripeToken
    end

	def orders_param
		params.require(:order).permit(:hug_id, :name, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hugs_helper.rb
module HugsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/hugs/create.html.haml
%h2 Thanks for your Payments!

app/views/hugs/index.html.haml
- @hugs.each do |hug|
	= link_to hug.name, hug

app/views/hugs/show.html.haml
%h2
  Package Name:
  = @hug.name
%p= @hug.description
%p
  $
  = @hug.price

= link_to "Order NOW", new_order_path(hug_id: @hug.id)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bearhugs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/create.html.haml
%h2 Thanks for your Payment! Your bears are on their ways!

app/views/orders/new.html.haml
= form_for @order do |f|
  = f.hidden_field :hug_id, value: @hug.id
  = f.label :name
  = f.text_field :name
  = f.label :email
  = f.text_field :email
  %script.stripe-button{"data-amount" => @hug.price*100, "data-description" => @hug.name, "data-key" => Rails.configuration.stripe[:publishable_key], "data-locale" => "auto", :src => "https://checkout.stripe.com/checkout.js"}